version: "3.6"
services:
  pokemon:
    build: ./php
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./php/src:/var/www/html/
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=myDB
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password 
    volumes:
      - ./db/:/docker-entrypoint-initdb.d